### ISSUE TITLE
BoxTensor Indexing

### ISSUE THREAD

**Issue by ruoshiliu** [iesl/box-embeddings#16]
Hi,

I'm new to the box embeddings. I'm wondering if the current implementation has some sort of indexing method? E.g. if a box tensor contains 64 16-dimensional boxes, what's the best way to access specific boxes in this tensor? I think constructing a new box tensor with `.from_zZ()` could work but just wondering if we can do this more efficiently.

Thanks!

**Comment by dhruvdcoder** [comment]
Hi @ruoshiliu. Sorry for the delayed response. Getting the `z` and `Z`, indexing them and subsequently, calling `.from_zZ()` seems like the most efficient way right now. We are planning on adding a convenience function that will combine these two steps for the users.
