### ISSUE TITLE
Cannot commit to personal branches due to precommit hook

### ISSUE THREAD

**Issue by mboratko** [iesl/box-embeddings#27]
Personal branches (other than `main` and `dev/main`) seem to still require precommit hooks to pass.

**Comment by dhruvdcoder** [comment]
You can use the `--no-verify` flag like so `git commit . -m 'quick fix' --no-verify` to skip all hooks of pre-commit. 
Ref: https://ma.ttias.be/git-commit-without-pre-commit-hook/

PS: I would say that you can do it in your branch, but would not recommend doing this very often even in your branch.
