### ISSUE TITLE
Should we be calling it an NLP library?

### ISSUE THREAD

**Issue by dhruvdcoder** [iesl/box-embeddings#53]
It is a general library that can be used for NLP or graph learning. Calling it an NLP library might be too restrictive. @mboratko @ssdasgupta What do you think?

**Comment by trangtran72** [comment]
Proposal: _An open-source research library for NLP or graph learning, built on PyTorch & TensorFlow_
Let me know if this sounds good

**Comment by dhruvdcoder** [comment]
Sounds good. Perhaps, 'NLP and graph learning'?

**Comment by mboratko** [comment]
Agree that NLP is too restrictive, I like the idea of NLP and graph learning.
