### ISSUE TITLE
Instead of clamping the input to `log` to a minimum eps, add an eps to the input.

### ISSUE THREAD

**Issue by dhruvdcoder** [iesl/box-embeddings#9]
https://github.com/iesl/box-embeddings/blob/76a5268330d9a47d9fad12fadec2df9bcda5b1b1/box_embeddings/modules/volume/soft_volume.py#L63

Clamping will kill the gradient. Adding a minimum eps will not.

**Comment by mboratko** [comment]
Oh yes, definitely. I thought this is already how we were doing it.
